=== ulricht01/PRI/1/DTD/student.dtd
<!ELEMENT univerzita (student+)>

<!ELEMENT student (jméno, příjmení, studentské_číslo, email, studijní_rok, rozvrh, předměty?, splněné_předměty?)>
<!ATTLIST student
    id ID #REQUIRED
>

<!ELEMENT jméno (#PCDATA)>
<!ELEMENT příjmení (#PCDATA)>
<!ELEMENT studentské_číslo (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT studijní_rok (#PCDATA)>
<!ELEMENT rozvrh (#PCDATA)>

<!ELEMENT předměty (předmět+)>
<!ELEMENT předmět (#PCDATA)>

<!ELEMENT splněné_předměty (splněný_předmět+)>
<!ELEMENT splněný_předmět (#PCDATA)>

=== ulricht01/PRI/1/DTD/student.xml
<!DOCTYPE student SYSTEM "student.dtd">

<student id="1">
    <jméno>Jan</jméno>
    <příjmení>Novák</příjmení>
    <studentské_číslo>123456</studentské_číslo>
    <email>jan.novak@example.com</email>
    <studijní_rok>2</studijní_rok>
    <rozvrh>pondělí 8:00 - 12:00, středa 14:00 - 16:00</rozvrh>
    <předměty>
    <předmět>Matematika</předmět>
    <předmět>Fyzika</předmět>
    <!-- další předměty -->
    </předměty>
    <splněné_předměty>
        <splněný_předmět>Anglický jazyk</splněný_předmět>
        <!-- další splněné předměty -->
    </splněné_předměty>
 </student>
